name = "proxyeverything-cf"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = [
    "nodejs_compat"
]

# 通用KV配置（所有环境继承）
kv_namespaces = [
  { binding = "BKLS_STORE", id = "8a39fb44a72a4aec97921cfac597d7d4" }
]

# 标记日志级别为INFO
[observability.logs]
enabled = true

# 生产环境配置
[env.production]
kv_namespaces = [
  { binding = "BKLS_STORE", id = "8a39fb44a72a4aec97921cfac597d7d4" }
]



# 生产环境构建配置
[env.production.build]
command = ""